
export enum EntityName {
    USER = 'users',
    ROLE = 'roles',
    USER_ROLE = 'user_roles',
    PERMISSION = 'permissions',
    ROLE_PERMISSION = 'role_permissions',
    CATEGORY = 'categories',
    POST = 'posts',
    POST_META = 'posts_meta',
    POST_VIEWS = 'post_views',
    POST_CATEGORY = 'post_categories',
    POST_FAVORITES = 'post_favorites',
    POST_COMMENT = 'post_comments',
    COURSE_CATEGORY = 'course_categories',
    COURSE_INSTRUCTOR = 'course_instructors',
    COURSE = 'courses',
    COURSE_CHAPTER = 'course_chapters',
    COURSE_COMMENT = 'course_comments',
    LESSON = 'lessons',
    COURSE_ENROLLMENT = 'course_enrollments',
    CART = 'carts',
    CART_ITEM = 'cart_items',
    ORDER = 'orders',
    ORDER_ITEM = 'order_items',
    PAYMENT_ATTEMPT = 'payment_attempts',
    AUTH_OTP_CHALLENGE = 'auth_otp_challenges',
    AUTH_SESSION = 'auth_sessions',
    DISCOUNT_CODE = 'discount_codes',
    DISCOUNT_CODE_USAGE = 'discount_code_usages',
    NOTIFICATION = 'notifications',
    CONTACT_MESSAGE = 'contact_messages',
}
